apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.fastApi.hpaName }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.fastApi.deploymentName }}
  minReplicas: {{ .Values.fastApi.hpaMinReplicas }}
  maxReplicas: {{ .Values.fastApi.hpaMaxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.fastApi.hpaTargetCPUUtilizationPercentage }}
