apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgres.pvc.name }}
spec:
  accessModes:
{{ toYaml .Values.postgres.pvc.accessModes | indent 2 }}
  resources:
    requests:
      storage: {{ .Values.postgres.pvc.resources.requests.storage }}
