apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.pgAdminService.serviceName }} 
spec:
  selector:
    app: {{ .Values.pgAdminService.selector.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.pgAdminService.port }}  # Port exposé par le service
      targetPort: {{ .Values.pgAdminService.targetPort }}  # Port du conteneur
  type: {{ .Values.pgAdminService.type }}
