apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresService.serviceName }}
spec:
  ports:
    - port: {{ .Values.postgresService.port }}
      targetPort: {{ .Values.postgresService.port }}
  selector:
    app: {{ .Values.postgresService.selector.app }}
